version: "3.9"
services:
  
  backend:
    build: backend/.
    container_name: backend
    ports:
      - "8000:8000"
    # expose:
    #   - 8000
    restart: unless-stopped
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    networks:
      - docker-ci-network
    links:
      - db
    env_file:
      - ./backend/.env
  db:
    image: postgres:15
    restart: always
    expose:
      - 5432
    env_file:
      - .db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - docker-ci-network

volumes:
  postgres_data:

networks:
  docker-ci-network:
    driver: bridge
