version: "3.9"
services:
  
  backend:
    build: backend/.
    container_name: backend
    ports:
      - "8000:8000"
    # expose:
    #   - 8000
    restart: unless-stopped
    volumes:
      - ./backend/:/backend/
    depends_on:
      - postgres
      - ml
    networks:
      - docker-ci-network
    links:
      - postgres
    env_file:
      - ./backend/.env
  ml:
    build: ml/.
    container_name: ml
    ports:
      - "8023:8000"
    restart: unless-stopped
    volumes:
      - ./ml/:/ml/
    depends_on:
      - postgres
    networks:
      - docker-ci-network
  postgres:
    image: postgres:15
    restart: always
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    env_file:
      - .db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - docker-ci-network
    hostname: db

volumes:
  postgres_data:

networks:
  docker-ci-network:
    driver: bridge
