"""base models #20

Revision ID: 07b52fdc3168
Revises: fabd9ba1efb9
Create Date: 2023-05-27 10:37:44.951024

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '07b52fdc3168'
down_revision = 'fabd9ba1efb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'additional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('additional', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
