"""base models #5

Revision ID: 1816114c5379
Revises: dc7e5fa363ea
Create Date: 2023-05-26 12:31:48.871574

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1816114c5379'
down_revision = 'dc7e5fa363ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
