"""base models #23

Revision ID: 1f549ae2ff1d
Revises: a9c69103ea87
Create Date: 2023-05-27 21:12:14.778261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1f549ae2ff1d'
down_revision = 'a9c69103ea87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraccount', sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('useraccount', 'patronymic')
    op.drop_column('useraccount', 'firstname')
    op.drop_column('useraccount', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraccount', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('useraccount', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('useraccount', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('useraccount', 'fullname')
    # ### end Alembic commands ###
