"""base models #6

Revision ID: 2551f5c5f7f2
Revises: 1816114c5379
Create Date: 2023-05-26 12:33:53.193082

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2551f5c5f7f2'
down_revision = '1816114c5379'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
