"""base models #17

Revision ID: 33cdf4f32314
Revises: b92842e8b45b
Create Date: 2023-05-27 10:20:22.866172

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33cdf4f32314'
down_revision = 'b92842e8b45b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('group_old_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'group_old_ids')
    # ### end Alembic commands ###
