"""base models #7

Revision ID: 39388795ca03
Revises: 2551f5c5f7f2
Create Date: 2023-05-26 12:42:27.127114

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '39388795ca03'
down_revision = '2551f5c5f7f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('old_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'old_id')
    # ### end Alembic commands ###
