"""base models #15

Revision ID: 458e0c55ed4d
Revises: 40afad8bf408
Create Date: 2023-05-27 10:17:54.628633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '458e0c55ed4d'
down_revision = '40afad8bf408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
