"""base models #11

Revision ID: 7eb65b112d4c
Revises: f33815528b37
Create Date: 2023-05-27 09:54:50.990713

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7eb65b112d4c'
down_revision = 'f33815528b37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
