"""base models #13

Revision ID: 8560231e65e3
Revises: d2bd4c7c9387
Create Date: 2023-05-27 10:10:21.582144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8560231e65e3'
down_revision = 'd2bd4c7c9387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('address', 'group_old_ids',
    #            existing_type=sa.INTEGER(),
    #            type_=postgresql.JSON(astext_type=sa.Text()),
    #            nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'group_old_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
