"""base models #21

Revision ID: 896ba68b0bb8
Revises: 07b52fdc3168
Create Date: 2023-05-27 10:57:11.476204

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '896ba68b0bb8'
down_revision = '07b52fdc3168'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupaddresslink',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'address_id')
    )
    op.drop_constraint('address_group_id_fkey', 'address', type_='foreignkey')
    op.drop_column('address', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('address_group_id_fkey', 'address', 'group', ['group_id'], ['id'])
    op.drop_table('groupaddresslink')
    # ### end Alembic commands ###
