"""base models #9

Revision ID: 9ab1918db980
Revises: 9aa57c2cbb26
Create Date: 2023-05-26 17:25:26.871743

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9ab1918db980'
down_revision = '9aa57c2cbb26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time_start', sa.Time(timezone=True), nullable=True),
    sa.Column('time_end', sa.Time(timezone=True), nullable=True),
    sa.Column('old_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('useraccount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['useraccount_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
