"""base models #22

Revision ID: a9c69103ea87
Revises: 896ba68b0bb8
Create Date: 2023-05-27 20:51:36.188774

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a9c69103ea87'
down_revision = '896ba68b0bb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraccount', sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('useraccount', sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('useraccount', sa.Column('patronymic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useraccount', 'patronymic')
    op.drop_column('useraccount', 'lastname')
    op.drop_column('useraccount', 'firstname')
    # ### end Alembic commands ###
