"""base models #16

Revision ID: b92842e8b45b
Revises: 458e0c55ed4d
Create Date: 2023-05-27 10:20:04.495474

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b92842e8b45b'
down_revision = '458e0c55ed4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'group_old_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('group_old_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
