"""base models #3

Revision ID: be38ab720f2e
Revises: 6f02c91b552a
Create Date: 2023-05-25 16:46:23.127898

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'be38ab720f2e'
down_revision = '6f02c91b552a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'old_id')
    op.drop_column('route', 'old_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('old_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('old_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
