"""poll models #2

Revision ID: c4a90fed59fb
Revises: 7505195b2951
Create Date: 2023-05-28 17:11:55.304035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4a90fed59fb'
down_revision = '7505195b2951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'text')
    # ### end Alembic commands ###
