"""base models #12

Revision ID: d2bd4c7c9387
Revises: 7eb65b112d4c
Create Date: 2023-05-27 10:06:45.572194

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd2bd4c7c9387'
down_revision = '7eb65b112d4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
