"""base models #4

Revision ID: dc7e5fa363ea
Revises: be38ab720f2e
Create Date: 2023-05-26 11:43:39.358713

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'dc7e5fa363ea'
down_revision = 'be38ab720f2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
