"""base models #10

Revision ID: f33815528b37
Revises: 9ab1918db980
Create Date: 2023-05-27 09:45:34.129618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f33815528b37'
down_revision = '9ab1918db980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('group_old_ids', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'group_old_ids')
    # ### end Alembic commands ###
