"""base models #19

Revision ID: fabd9ba1efb9
Revises: 13c9cfd225a9
Create Date: 2023-05-27 10:27:29.423762

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fabd9ba1efb9'
down_revision = '13c9cfd225a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('group_old_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'group_old_id')
    # ### end Alembic commands ###
